server:
  port: 8081  # 设置服务器的端口为 8081

spring:
  datasource:
    url: jdbc:postgresql://192.168.100.100:5432/postgres?currentSchema=public
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: org.dev1.model



logging:
  level:
    org.springframework.web: DEBUG  # 设置日志级别为 DEBUG

